name: hello-world
on: push
env:
  DAY_OF_WEEK: Monday
  
jobs:
  my-job:
    runs-on: ubuntu-latest
    env: 
      user_key: ${{ secrets.user_key }}
    steps:
      - name: my-step
        if:  $user_key == 'abcd'
        run: echo "Hello World! Today is $DAY_OF_WEEK!"
