name: hello-world
on: push
jobs:
  my-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: my-step
        run: echo "Hello world Today is Monday!"
